### ISSUE TITLE
Geller not finding *defined* variables

### ISSUE THREAD

**Issue by AugusDogus** [cmgriffing/geller#3]
There's a "minimal" reproduction available at [AugusDogus/geller-issue-reproduction](https://github.com/AugusDogus/geller-issue-reproduction). 

![image](https://user-images.githubusercontent.com/9794679/227669892-14fbbdd5-4cfe-4232-beb5-eb914f73bd5d.png)

![image](https://user-images.githubusercontent.com/9794679/227670504-38d42454-3413-40b1-9d90-b1b31f344d48.png)

![image](https://user-images.githubusercontent.com/9794679/227671003-e58c360a-7520-4d47-91f0-9e4e95dc8d25.png)

![image](https://user-images.githubusercontent.com/9794679/227670120-13048a62-4b22-4917-9383-d9e775d427f8.png)

**Comment by cmgriffing** [comment]
Thanks for the repro repo.

It turns out that I hadn't done a build before publishing the env var changes. I have updated the version to 0.1.2.

I have also added the build to a prepublish step that should prevent this exact in the future.

After updating my version in your repro repo, it works as expected.
